create: 37장 Set과 Map
ritajeong/javascript-study pull request #29
Opened 2021-10-25 13:13 UTC by ritajeong

늦어서 죄송합니다ㅜㅜ

2021-10-30 22:07 UTC, yujo11 approved these changes
고생하셨습니다! 👍 👍 👍

2021-10-31 04:08 UTC, ssmin0606 commented
고생하셨습니다!

2021-10-31 04:09 UTC, ssmin0606 approved these changes
고생하셨습니다!

2021-10-31 04:43 UTC, ssmin0606 commented on 37장-Map/README.md
> +- 일치 비교 연산자를 사용하면 NaN과 NaN은 다르다고 평가됨. 그러나 Set 객체는 이를 같다고 평가하여 중복 추가를 허용하지 않음. +0과 -0도 같은 맥락으로 허용하지 않음.
여기서 Set 객체가 아니고 Map 객체 인 것 같습니다! 확인 후 맞으면 수정 해주시면 좋을 것 같아요

2021-10-31 05:13 UTC, ssmin0606 requested changes
Set -> Map 확인해주시면 감사하겠습니다.

2021-10-31 05:17 UTC, ssmin0606 requested changes
코멘트 단 것만 확인해주시면 좋을 것 같습니다.
깔끔한 정리 감사합니다!

2021-11-01 01:09 UTC, ritajeong commented on 37장-Map/README.md
> +- 일치 비교 연산자를 사용하면 NaN과 NaN은 다르다고 평가됨. 그러나 Set 객체는 이를 같다고 평가하여 중복 추가를 허용하지 않음. +0과 -0도 같은 맥락으로 허용하지 않음.
수정했습니다! 꼼꼼한 확인 감사합니다 ~~

2021-11-01 01:09 UTC, merged