40장 이벤트 정리
ritajeong/javascript-study pull request #31
Opened 2021-10-31 00:46 UTC by yujo11

분량이 많아 최대한 요약해볼려고 노력했습니다.

- [편하게 보기](https://github.com/yujo11/javascript-study/tree/master/40%EC%9E%A5-%EC%9D%B4%EB%B2%A4%ED%8A%B8)

2021-10-31 04:36 UTC, ssmin0606 commented on 40장-이벤트/README.md
> +- **생성된 이벤트 객체는 이벤트 핸들러의 첫 번째 인수로 전달된다. **
글 굵게 하기 기능이 잘 적용되지 않는 것 같습니다! 확인 부탁드려요

2021-10-31 04:37 UTC, ssmin0606 commented on 40장-이벤트/README.md
> +- 이벤트 객체는 Event, UIEvent, MouseEvent 등과 같은 이벤트 생성자 함수로 쇼ㅐㅇ성할 수 있다.
오타 있습니다. 수정 해주시면 좋을 것 같습니다.

2021-10-31 04:38 UTC, ssmin0606 requested changes
오타 있어서 고쳐주시면 완벽할 것 같습니다.
이벤트에 대해서 정리 깔끔하게 잘 해주셨어요 수고하셨습니다!

2021-10-31 11:10 UTC, yujo11 commented
상민님 리뷰 반영 했습니다 감사합니다! 👍 👍👍

2021-11-07 04:32 UTC, ssmin0606 approved these changes

2021-11-08 02:33 UTC, Tanney-102 commented
와우.. 많은 양을 요약하느라 고생하셨습니다 ㅎㅎ

2021-11-08 23:30 UTC, ritajeong approved these changes
중요한 내용을 잘 요약정리해주셔서 많은 도움이 되었습니다! 감사합니다

2021-11-11 11:45 UTC, merged