39장 DOM 전반부 작성
ritajeong/javascript-study pull request #33
Opened 2021-11-03 04:01 UTC by Tanney-102

[링크](https://github.com/ritajeong/javascript-study/tree/tanney/39%EC%9E%A5-DOM)

2021-11-07 01:36 UTC, yujo11 approved these changes
깔끔하게 잘 정리해주셨네요!

감사합니다 태은님! 👍👍👍

2021-11-07 04:22 UTC, ssmin0606 commented on 39장-DOM/README.md
> +![노드객체구조](https://user-images.githubusercontent.com/57767891/139620868-a2dcc469-1b34-40e6-9493-bff3d27200dd.png)
여기 줄 한 번 띄워주면 좋을 것 같아요!!
지금은 `다음과 같다` 이후에 이미지가 바로 이어서 나오는데 그 밑에 나오면 더 좋을 것 같습니다!

2021-11-07 04:22 UTC, ssmin0606 requested changes
요약 잘해주셔서 감사합니다!

이미지 줄 관련하여 코멘트 남긴 거 한 번 봐주시면 감사하겠습니다!

2021-11-08 02:25 UTC, Tanney-102 commented on 39장-DOM/README.md
> +![노드객체구조](https://user-images.githubusercontent.com/57767891/139620868-a2dcc469-1b34-40e6-9493-bff3d27200dd.png)
오오 날카로운 지적 감사합니다!!! 수정 했습니다 ㅎㅎ [commit](https://github.com/ritajeong/javascript-study/pull/33/commits/b86b4b381cdd99eeacc3b17bc584354dc9e14ff4)

2021-11-08 23:36 UTC, ritajeong approved these changes
간단명료하게 정리해주셔서 읽기 편했습니다 감사합니다 ㅎㅎ

2021-11-14 13:03 UTC, ssmin0606 approved these changes
수정 감사합니다!

2021-11-17 04:03 UTC, merged